### ISSUE TITLE
default template is not set up properly

### ISSUE THREAD

**Issue by brecert** [12Boti/nix-minecraft#9]
```console
$ nix flake init -t github:12Boti/nix-minecraft
error: cannot find flake attribute 'github:12Boti/nix-minecraft#defaultTemplate'

$ nix flake init -t github:12Boti/nix-minecraft#default
$ cat flake.nix
{
  inputs.nix-minecraft.url = "github:12Boti/nix-minecraft";
  ...
}
```

You just need to switch from `templates.default` to `defaultTemplate`

**Comment by 12Boti** [comment]
It got changed in nix 2.7.0. (I know that version is still new, but I wanted it to `nix flake check` without warnings.) I'll put a notice in the readme for those who haven't upgraded yet.

**Comment by brecert** [comment]
Ah I didn't know that. Thanks!
